name: Build and Release TubeTweaks

on:
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: "Direct URL of the decrypted YouTube ipa"
        default: ""
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build TubeTweaks
    runs-on: macos-15
    permissions:
      contents: write
    env:
      BUNDLE_ID: com.google.ios.youtube
      APP_NAME: YouTube

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: iOS SDK Caching
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Set GNU Make Path
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          (echo export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" >> ~/.bash_profile)
          source ~/.bash_profile

      - name: Download YouTube IPA
        run: |
          curl -L -o YouTube.ipa "${{ github.event.inputs.decrypted_youtube_url }}"
          echo "YT_VERSION=$(unzip -p YouTube.ipa 'Payload/YouTube.app/Info.plist' | plutil -extract CFBundleVersion raw -)" >> $GITHUB_ENV

      - name: Install cyan
        run: pip install --force-reinstall https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip Pillow

      - name: Build Packages
        run: |
          make package FINALPACKAGE=1
          cyan -duwsgq -i YouTube.ipa -o TubeTweaks_${{ env.YT_VERSION }}.ipa -f packages/*.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.YT_VERSION }}
          files: TubeTweaks_${{ env.YT_VERSION }}.ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update app-repo.json
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          IPA_SIZE=$(ls -l TubeTweaks_${{ env.YT_VERSION }}.ipa | awk '{print $5}')
          DOWNLOAD_URL=https://github.com/${{ github.repository }}/releases/download/v${{ env.YT_VERSION }}/TubeTweaks_${{ env.YT_VERSION }}.ipa
          NEW_ENTRY=$(jq -n --arg version "${{ env.YT_VERSION }}" --arg date "$DATE" --arg size "$IPA_SIZE" --arg downloadURL "$DOWNLOAD_URL" '{version: $version, date: $date, size: ($size | tonumber), downloadURL: $downloadURL}')
          jq --argjson newEntry "$NEW_ENTRY" '.apps[0].versions |= [$newEntry] + .' app-repo.json > temp.json && mv temp.json app-repo.json

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update app-repo.json"
          add: app-repo.json

      - name: Job Summary
        run: |
          echo -e '### 📺 Build Complete' >> $GITHUB_STEP_SUMMARY
