name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote --force
          git add .
          git commit -m "updated submodules" || echo "No changes to commit"
          git push origin || echo "No changes to push"
